### ISSUE TITLE
Zeiten schöner darstellen.

### ISSUE THREAD

**Issue by cnoss** [th-koeln/wba1-2016-semaphore#115]
Ich hab die Zeit an einer Stelle mal schöner dargestellt. Das sollte an allen Stellen so gemacht werden, sprich: es wäre gut dafür eine Funktion zu haben. Jemand Lust und Zeit?

https://github.com/th-koeln/wba1-2016-semaphore/commit/4f90c8eebfdea987305ad4c645fe950e4b6d9f84

**Comment by DennisNew1** [comment]
Ich nehm mir das mal vor. 
Allerdings hab ich im Moment keine Ahnung welche unsere aktuelleste Datei ist da wir zwei Index Dateien haben. Einmal in app und eine in app/quizapp. Beide funktionieren nicht so weit wie ich das im Kopf hatte. Das heißt ich kann nicht nachschauen ob es geht.
Außerdem weiß ich auch nicht in welche .js ich das packen soll. Das ist übergreifend und passt nicht so recht in die bisherigen JavaScript Dateien.

**Comment by cnoss** [comment]
Gucken wir morgen mal zusammen drauf. Haben Sie einen lokalen Webserver am Start?

**Comment by mariofaske** [comment]
Hab die Funktion einfach mal im PreLoader.js hinzugefügt. Kann man jederzeit noch verschieben.
