### ISSUE TITLE
Welches Highscoreliste wird angezeigt?

### ISSUE THREAD

**Issue by cnoss** [th-koeln/wba1-2016-semaphore#131]
Auf der Hightscoreseite zeigt das Dropdownfeld nicht das ausgewählte Quiz, sondern das erste. Könnten Sie da bitte noch mal gucken? Danke!

**Comment by FloMarks** [comment]
Das Dropdown-Menü hat vor der dynamischen Füllung funktioniert. Wir wissen leider nicht, wie wir das Problem beheben können und hoffen, dass das Zusammenführungsteam eine Lösung finden kann. Wir fügen dieses als Label hinzu.

**Comment by cnoss** [comment]
ok

**Comment by mariofaske** [comment]
Funktioniert wieder! Danke an den Problemlöser(cnoss?).
