### ISSUE TITLE
Wichtig: Festgelegte Breakpoints!

### ISSUE THREAD

**Issue by vseetohu** [th-koeln/wba1-2016-semaphore#16]
Mobile/Smart phone: 439 px
Tablet: 1024 px
Übersicht über verwendete Tags/Klassen/IDs und zusätzliche Infos auf unserer Gruppenseite: http://tinyurl.com/h3ryra6

**Comment by abuesche** [comment]
fertig Startscreen

**Comment by cnoss** [comment]
die sollten bitte in die Base.scss übernommen werden, falls noch nicht geschehen.

**Comment by vseetohu** [comment]
Die Breakpoints sind schon in der Base.scss übernommen wurden.
