### ISSUE TITLE
HTML/CSS Highscore an Styleguide anpassen, Bilder einfügen

### ISSUE THREAD

**Issue by simonezjc** [th-koeln/wba1-2016-semaphore#24]

**Comment by MarinaB86** [comment]
https://github.com/th-koeln/wba1-2016-semaphore/blob/master/grafiker/hintergrund-Highscoreliste_handygroesse%20mit%20schraegem%20balken.png

Dies ist das Hinterrgundbild (Handy )für den Highscore-Screeen. 
Schaut mal bitte ob ihr das so nutzen könnt wegen dem abgeschrägtem. Solltet ihr ein längeres Bild benötigen mit weißem Hintergrund im unteren Teil, einfach kurz bescheid sagen.
