### ISSUE TITLE
Assets und Bilder einbauen

### ISSUE THREAD

**Issue by mschamber** [th-koeln/wba1-2016-semaphore#27]

**Comment by MarinaB86** [comment]
Schaut mal ob ihr damit was anfangen könnt, ansonsten kurz bescheid geben, dann machen wir euch eine Grafik daraus. (Das war ein Tipp vom Herrn Noss, das man sowas für die Icons verwenden kann)
http://fontawesome.io/icon/user-circle-o/

Ansonsten findet ihr im Laufe des Abends auf unserer wiki-Seite noch weitere Icons und Bilder.
