### ISSUE TITLE
Ablagemöglichkeit für die Grafiken

### ISSUE THREAD

**Issue by MarinaB86** [th-koeln/wba1-2016-semaphore#39]

**Comment by cnoss** [comment]
Ähm … was muss ich da machen?

**Comment by ChiaraSchmeis** [comment]
Es ging darum, wie wir die Bilder in GitHub speichern können. Das sollte sich aber jetzt geklärt haben! Die ersten Bilder befinden sich nun im grafiker-Ordner und verlinkt auch auf unserer Seite.
