### ISSUE TITLE
Form der Ausarbeitung

### ISSUE THREAD

**Issue by TobiasRutsch** [th-koeln/wba1-2016-semaphore#44]
Wir wollen sicher gehen, dass wir nicht an der Aufgabe vorbei arbeiten. Im Wiki findet man auf unserer Seite eine Liste von Marketingtools. Wir werden uns mit jedem dieser Themen auseinandersetzten und prüfen, ob diese mehr oder weniger gut für unser Projekt geeignet sind. Sofern möglich werden wir die Punkte auch umsetzen. (z.B SEO). Dazu wird dann ein Berricht verfasst, der als eine Art Konzept fungiert und beinhaltet welche Methoden sich anbieten, wie man diese umsetzen kann und worauf man achten muss. Darüber hinaus erstellen wir eine funktionierende Landingpage.
Falls noch weitere Aufgaben anstehen oder das Marketingkonzept in anderer Form ausgearbeitet werden soll, bitten wir um Rückmeldung.

**Comment by cnoss** [comment]
Ok.. ich würde den Stand der Forschungen erst mal so stehen lassen und zeitnah überlegen, wie eine konkrete Landingpage für dieses Projekt aussehen soll und diese auch umsetzen. Vorab natürlich mit mir besprechen und in der Company vorstellen. Idealerweise nächste Woche. Und dann ihr Know-How darin einfließen lassen und das nachher dokumentiert. ok? Können wir Dotag noch mal drüber sprechen. Oder sie skypen mich vorab mal an (c.noss)
