### ISSUE TITLE
Neues Arbeitspaket bekommen oder an gleichem Screen weiterarbeiten?

### ISSUE THREAD

**Issue by kgaarz** [th-koeln/wba1-2016-semaphore#48]
Wie im Peer-Review besprochen ist das Problem aufgetreten, dass Team Startscreen und Team Highscore am selben Screen gearbeitet haben (und auch vom Arbeitsstand auf dem gleichen Level sind). Hier nun die Frage, ob ein neues Arbeitspaket/Screen geplant ist und wie mit diesem Problem weiter umgegangen werden soll um die Woche effektiv nutzen zu können.

**Comment by cnoss** [comment]
Bitte am Startscreen weiter machen und die eingebettete Highscoreliste nicht berücksichtigen. Die würden wir dann vom anderen Team nehmen, ok? Es gibt für das Smartphone da ja noch so einen "Mehr lesen" Pfeil. Da können Sie ja auch schon mal ran gehen, ok? bei Unklarheiten melden bitte.

[MOCKUP FUBUIZZ by UPSIDEDOWN (verschoben).pdf](https://github.com/th-koeln/wba1-2016-semaphore/files/561304/MOCKUP.FUBUIZZ.by.UPSIDEDOWN.verschoben.pdf)
