### ISSUE TITLE
Callback probleme mit dem request, lässt sich nicht entkoppeln

### ISSUE THREAD

**Issue by TimSchuerheck** [th-koeln/wba1-2016-semaphore#77]
Tach,
ich bin heute auf ein Problem gestoßen. Das Script, das beim laden der Seite die nötigen HTML Dokumente in den Browsercache läd; es lässt sich nicht vom einspeisen der Daten in den Dombaum entkoppeln. Ich vermute es liegt an dem Asynchronen verhalten von der XMLHttpRequest klasse.
Ich werde das erstmal ohne einmaliges laden der HTML seiten weiter schreiben, damit wir bis zum nächsten Donnerstag etwas haben womit das Zusammenfüger-Team arbeiten kann. Allerdings würde es die One-Pager Lösung relativ witzlos machen, wenn die Requests ja doch beim Seitenwechsel passieren.

**Comment by cnoss** [comment]
ok ... kann ich irgendwo code dazu sehen? oder sollen wir heute mal dazu skypen?

**Comment by TimSchuerheck** [comment]
In diesem [script](https://github.com/th-koeln/wba1-2016-semaphore/blob/loadInOnePage/app/assets/js/loader.js) hatte ich das Problem. Ich konnte am ende des scripts den geladenen Text nicht ausgeben. Zumindest nicht so wie ich es erwartet hatte. Ich hab versucht die open methode mit synchron laufen zu lassen, das hat auch nicht geholfen. Vielleicht liegt das Problem auch daran, dass ich was mit den Funktionsrückgabe Werten falsch gemacht habe, wegen der verschachtelten Funktion. Ich hab leider heute keine Zeit zu skypen, meine Eltern kommen mich nachher besuchen. Ich würde das bis Donnerstag erstmal so weiter machen wie Sie es uns gezeigt haben. Wir können dann immernoch darüber reden. Jetzt ist mir erstmal wichtig, dass die Seiten und die Jsons irgendwie dynamisch geladen und eingespeist werden, damit das verantwortliche Team auf JS Ebene alles zur verfügung hat um die statischen HTML/CSS Seiten zusammenzuführen.

**Comment by cnoss** [comment]
Ok ... ich schau mir das nachher trotzdem mal an … schönen Tag noch.

**Comment by cnoss** [comment]
Sie haben übringens Ihren Block liegen gelassen. Der liegt jetz bei mir im Büro :)

**Comment by DavidBajon** [comment]
Tim ändere mal "/data/quizuebersicht.json" auf
http://wba1-semaphore.christiannoss.de/app/data/quizuebersicht.json

2016-11-06 13:06 GMT+01:00 Christian Noss <notifications@github.com>:

**Comment by cnoss** [comment]
Ist das Problem noch virulent. Falls ja, bitte noch mal melden. Bin noch bis 20:00 Uhr am Platz und morgen von 7 bis 11 … danach leider in Meetings. Issues checke ich aber.

**Comment by TimSchuerheck** [comment]
> vi·ru·lẹnt  
> Adjektiv
> [nicht steig.]med. ansteckend, krankheitserregend.

Falls sie das mit den Callback meinen, das ist erstmal unter quarantäne. Die andere Sache scheint zu funktionieren.

**Comment by cnoss** [comment]
jut

**Comment by TimSchuerheck** [comment]
Wenn Sie aber noch Zeit haben, wäre es schon hilfreich wenn wir kurz Skypen. Rufen Sie an wenn es noch passt. +491604186434

**Comment by cnoss** [comment]
sry. nicht mehr gesehen. morgen früh? mein Skypeuser ist c.noss

**Comment by TimSchuerheck** [comment]
Kein Problem. Morgen früh müsste gehen. Ich melde mich dann, denke so gegen
9 vielleicht früher.

**Comment by TimSchuerheck** [comment]
Noss hat uns [dieses Script](https://github.com/th-koeln/wba1-2016-semaphore/blob/loadInOnePage/app/assets/js/getTemplates.js) geschrieben, dass alle nötigen Templates zieht. Theoretisch ist jetzt auch alles geklärt.

Ich muss halt einfach alle Aktionen die erst passieren sollen wenn alles geladen ist in die Callbackfunktion schreiben. Oder ich lege ein boolean an der alle weiteren user input events verhindert solange nicht alles geladen ist. Wobei die erste Startseite im Callback liegen muss.

Das Issue bleibt aber offen bis es auch praktisch funktioniert hat.

Javascript Programmierung ist sonderbar.

**Comment by TimSchuerheck** [comment]
So, das wäre jetzt auch erledigt. In der preloader.js Datei wird nun alles geladen und dann in den jeweiligen create(..) Methoden, die sich in gleichnamigen Dateien befinden sollten weiterverarbeitet.
