### ISSUE TITLE
Request der Jsons über wba1-semaphore.christiannoss.de -> Access to restricted URI denied

### ISSUE THREAD

**Issue by TimSchuerheck** [th-koeln/wba1-2016-semaphore#78]
Wenn ich die Jsons via localhost abfrage funktioniert alles ohne Probleme.
Sobald ich haber versuche ohne localhost einen Request an "wba1-semaphore.christiannoss.de" anzufordern, erhalte ich die Fehlermeldung "NS_ERROR_DOM_BAD_URI: Access to restricted URI denied".

@DavidBajon hat das nicht mal bei dir funktioniert?

Das ist der genaue Pfad den ich angegeben habe:
"http://wba1-semaphore.christiannoss.de/app/data/quizuebersicht.json";

**Comment by TimSchuerheck** [comment]
...Mir ist grade aufgefallen, dass es egal ist ob ich den localen pfad angebe oder den Direktlink.
Die Fehlermeldung kommt immer ohne localhost, ich geh jetzt mal einfach davon aus, dass das mit der Freigabe der Dateien funktioniert.

**Comment by cnoss** [comment]
Ich hab im Zweig loadInOnePage den loader angepasst und einen Testaufruf in der index.html gemacht. Ich hoffe das hilft. Sonst noch mal melden bitte. Ergebnis kann man auch hier sehen:
http://wba1-semaphore.christiannoss.de/app/quiz_app/

Das sieht doch insgesamt schon real fine aus!

**Comment by TimSchuerheck** [comment]
Danke! Die urls funktionieren, ich schließe das Issue.
