### ISSUE TITLE
Miese Organisation führt zu redundanter Arbeit

### ISSUE THREAD

**Issue by TimSchuerheck** [th-koeln/wba1-2016-semaphore#81]
Ich habe gerade erfahren, dass das Script an dem ich am Wochenende geschrieben habe parallel von @mariofaske geschrieben wurde. Was ist das hier, eine Company oder ein Rattenrennen?

**Comment by mariofaske** [comment]
Hallo, 
vielleicht vertue ich mich da, aber wir saßen doch am Donnerstag mit Herrn Noss am Ende am Tisch und haben geklärt wer was macht. David vom Logik-Team hat die Funktionen mit den AJAX Requests aufgebaut und das Team Zusammenführung hat die Aufgabe, das Javascript so zu erweitern, das die Daten aus den JSON´s in die HTML-Snippets geschrieben werden.
Ich habe am Wochende den Aufbau der Übersichtsseite sowie des Startscreens gemacht. Beim Startscreen sitze ich zurzeit noch daran, wie man die Highscoreliste zu dem gewählten Quiz mit Daten füllt.

**Comment by cnoss** [comment]
Hey Leute, bitte hier kein rumgestänkere! Wenn Probleme gibt: klären. Ansonsten gilt wie immer: sprechen. Bitte morgen mal zusammensetzen/-skypen... gucken wer wie weit gekommen ist, zusammenschmeißen oder auswählen und weiter gehts. Wenn ich helfen kann: bin bis 11:00 da, danach in Veranstaltungen.

**Comment by mariofaske** [comment]
Wir haben das per email besprochen. Tim hat nicht alles umsonst gemacht, wir werden 2 bzw 3 seiner Javascripte verwenden und uns am donnerstag nochmal über das weiter vorgehen unterhalten. Gute Nacht

**Comment by cnoss** [comment]
Alles klar. Guts Nächtle.

**Comment by TimSchuerheck** [comment]
Kann schon sein das ich das vercheckt habe. Wir machen das beste draus.
