### ISSUE TITLE
Platzhalter im Template Quizübersicht abgleichen

### ISSUE THREAD

**Issue by cnoss** [th-koeln/wba1-2016-semaphore#97]
Hier bitte die Platzhalter im Template so umbenennen, dass sie korrekt ersetzt werden:
http://wba1-semaphore.christiannoss.de/app/quiz_app/

Template liegt hier:
git/wba1-2016-semaphore/app/quiz_app/quizuebersicht/quizuebersicht.html

Platzhalter können hiermit abgeglichen werden:
git/wba1-2016-semaphore/app/assets/js/createUbersicht.js

**Comment by TimSchuerheck** [comment]
Habe die Platzhalternamen im Script umbenannt, die passen jetzt auch hier.
