### ISSUE TITLE
Platzhalter im Startscreen Template

### ISSUE THREAD

**Issue by cnoss** [th-koeln/wba1-2016-semaphore#98]
Hier bitte die Platzhalter im Template so umbenennen, dass sie korrekt ersetzt werden:
http://wba1-semaphore.christiannoss.de/app/quiz_app/

Template liegt hier:
git/wba1-2016-semaphore/app/quiz_app/startscreen/startscreen.html

Platzhalter können hiermit abgeglichen werden:
git/wba1-2016-semaphore/app/assets/js/createStartscreen.js

Ich glaube es gibt eine aktuellere Version des Templates. Diese bitte unter git/wba1-2016-semaphore/app/quiz_app/startscreen/startscreen.html hinterlegen. Außerdem bitte das CSS noch mal überarbeiten. Wenn Sie Support brauchen: melden bitte.

Außerdem wäre es git, wenn das Highscore Team hier die Highscoreliste dynamisch aufbauen könnte. Bitte absprechen, falls da noch vorab Templates ausgetauscht werden müssen. Bei der dynamischen Highscoreliste kann ggf. Tim supporten.

**Comment by TimSchuerheck** [comment]
Müsste jetzt laufen

**Comment by cnoss** [comment]
awesome!

**Comment by TimSchuerheck** [comment]
Hab doch noch was übersehen, sorry

**Comment by TimSchuerheck** [comment]
jetzt aber
